# Generated by Django 5.2.5 on 2025-09-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_alter_dish_name_alter_ingredient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='name',
            new_name='dish_name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='ingredient_name',
        ),
    ]
