# Generated by Django 5.2.5 on 2025-09-08 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_rename_name_dish_dish_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='incompatible_with',
        ),
        migrations.CreateModel(
            name='Incompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(choices=[(1, 'Nhẹ'), (2, 'Vừa'), (3, 'Nặng')])),
                ('description', models.TextField(blank=True)),
                ('ingredient1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibility_ingredient1', to='foodapp.ingredient')),
                ('ingredient2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibility_ingredient2', to='foodapp.ingredient')),
            ],
            options={
                'unique_together': {('ingredient1', 'ingredient2')},
            },
        ),
    ]
