# Generated by Django 5.2.5 on 2025-09-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_remove_ingredient_incompatible_with_incompatibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='incompatible_with',
            field=models.ManyToManyField(blank=True, through='foodapp.Incompatibility', to='foodapp.ingredient'),
        ),
    ]
