# Generated by Django 5.2.5 on 2025-09-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_ingredient_incompatible_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_category',
            field=models.CharField(choices=[('soup', 'món canh'), ('main', 'món mặn'), ('boiled', 'món luộc')], default='món mặn'),
            preserve_default=False,
        ),
    ]
