# Generated by Django 5.2.5 on 2025-09-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_dish_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_category',
            field=models.CharField(choices=[('soup', 'món canh'), ('main', 'món mặn'), ('boiled', 'món luộc'), ('vegetarian', 'món chay')]),
        ),
    ]
