# Generated by Django 5.2.5 on 2025-09-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_category_ingredient_ingredient_ingredient_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incompatibility',
            new_name='Incompatibility_Ingredient',
        ),
    ]
