# Generated by Django 5.2.5 on 2025-09-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_rename_incompatibility_incompatibility_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_ingredient',
            options={'verbose_name': 'Ingredient category', 'verbose_name_plural': 'Ingredient category'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Dish', 'verbose_name_plural': 'Dish'},
        ),
        migrations.AlterModelOptions(
            name='incompatibility_ingredient',
            options={'verbose_name': 'Ingredient incompatibility', 'verbose_name_plural': 'Ingredient incompatibility'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredient'},
        ),
        migrations.AlterUniqueTogether(
            name='incompatibility_ingredient',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_category',
            field=models.CharField(choices=[('soup', 'món canh'), ('main', 'món mặn'), ('boiled', 'món luộc'), ('steamed', 'món hấp'), ('vegetarian', 'món chay'), ('stirfry', 'món xào'), ('braised', 'món kho')]),
        ),
        migrations.CreateModel(
            name='Dish_Vegetarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_vegetarian_name', models.CharField(max_length=100)),
                ('dish_vegetarian_category', models.CharField(choices=[('soup', 'món canh'), ('stirfry', 'món xào'), ('boiled', 'món luộc'), ('steamed', 'món hấp')])),
                ('ingredients', models.ManyToManyField(to='foodapp.ingredient')),
            ],
            options={
                'verbose_name': 'Vegetarian dish',
                'verbose_name_plural': 'Vegetarian dish',
            },
        ),
    ]
