# Generated by Django 5.2.5 on 2025-09-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0010_alter_category_ingredient_options_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_category',
            field=models.CharField(choices=[('soup', 'món canh'), ('stirfry', 'món xào (kho)'), ('fry', 'món chiên'), ('boiled', 'món luộc (hấp)'), ('main', 'món mặn'), ('vegetarian', 'món chay')]),
        ),
        migrations.AlterField(
            model_name='dish_vegetarian',
            name='dish_vegetarian_category',
            field=models.CharField(choices=[('soup', 'món canh'), ('stirfry', 'món xào (kho)'), ('fry', 'món chiên'), ('boiled', 'món luộc (hấp)')]),
        ),
    ]
