# Generated by Django 5.2.5 on 2025-09-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0011_alter_dish_dish_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_category',
            field=models.CharField(choices=[('soup', 'món canh'), ('stirfry', 'món xào (kho)'), ('fried', 'món chiên'), ('boiled', 'món luộc (hấp)')]),
        ),
    ]
