# Generated by Django 5.2.5 on 2025-09-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0012_alter_dish_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_vegetarian',
            name='dish_vegetarian_category',
            field=models.CharField(choices=[('soup', 'món canh'), ('stirfry', 'món xào (kho)'), ('fried', 'món chiên'), ('boiled', 'món luộc (hấp)')]),
        ),
    ]
