# Generated by Django 5.2.5 on 2025-10-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0013_alter_dish_vegetarian_dish_vegetarian_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='incompatible_with',
            field=models.ManyToManyField(blank=True, null=True, through='foodapp.Incompatibility_Ingredient', to='foodapp.ingredient'),
        ),
    ]
