# Generated by Django 5.2.5 on 2025-10-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0014_alter_ingredient_incompatible_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='incompatible_with',
            field=models.ManyToManyField(blank=True, through='foodapp.Incompatibility_Ingredient', to='foodapp.ingredient'),
        ),
    ]
