# Generated by Django 5.2.5 on 2025-09-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avata',
            field=models.FileField(blank=True, null=True, upload_to='avata/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.FileField(blank=True, null=True, upload_to='post/'),
        ),
    ]
